using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EzCraftModManager.Models;
using Newtonsoft.Json;

namespace EzCraftModManager.Services;

public class ProfileService
{
    private readonly string _profilesPath;
    private List<ServerProfile>? _cachedProfiles;

    public ProfileService()
    {
        var appDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "EzCraftModManager");
        Directory.CreateDirectory(appDataPath);
        _profilesPath = Path.Combine(appDataPath, "profiles.json");
    }

    public async Task<List<ServerProfile>> GetAllProfilesAsync()
    {
        if (_cachedProfiles != null) return _cachedProfiles;

        try
        {
            if (File.Exists(_profilesPath))
            {
                var json = await File.ReadAllTextAsync(_profilesPath);
                _cachedProfiles = JsonConvert.DeserializeObject<List<ServerProfile>>(json) ?? new List<ServerProfile>();
            }
            else
            {
                _cachedProfiles = new List<ServerProfile>();
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error loading profiles: {ex.Message}");
            _cachedProfiles = new List<ServerProfile>();
        }

        return _cachedProfiles;
    }

    public async Task<ServerProfile?> GetProfileAsync(string id)
    {
        var profiles = await GetAllProfilesAsync();
        return profiles.FirstOrDefault(p => p.Id == id);
    }

    public async Task SaveProfileAsync(ServerProfile profile)
    {
        var profiles = await GetAllProfilesAsync();

        var existingIndex = profiles.FindIndex(p => p.Id == profile.Id);
        if (existingIndex >= 0)
        {
            profiles[existingIndex] = profile;
        }
        else
        {
            profiles.Add(profile);
        }

        await SaveAllProfilesAsync(profiles);
    }

    public async Task DeleteProfileAsync(string id)
    {
        var profiles = await GetAllProfilesAsync();
        profiles.RemoveAll(p => p.Id == id);
        await SaveAllProfilesAsync(profiles);
    }

    private async Task SaveAllProfilesAsync(List<ServerProfile> profiles)
    {
        try
        {
            var json = JsonConvert.SerializeObject(profiles, Formatting.Indented);
            await File.WriteAllTextAsync(_profilesPath, json);
            _cachedProfiles = profiles;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Error saving profiles: {ex.Message}");
            throw;
        }
    }

    public async Task CreateServerFilesAsync(ServerProfile profile)
    {
        Directory.CreateDirectory(profile.ServerPath);
        Directory.CreateDirectory(profile.ModsPath);
        Directory.CreateDirectory(Path.Combine(profile.ServerPath, "config"));
        Directory.CreateDirectory(Path.Combine(profile.ServerPath, "world"));
        Directory.CreateDirectory(Path.Combine(profile.ServerPath, "logs"));
        Directory.CreateDirectory(Path.Combine(profile.ServerPath, "backups"));

        // Create server.properties
        await CreateServerPropertiesAsync(profile);

        // Create EULA
        await File.WriteAllTextAsync(Path.Combine(profile.ServerPath, "eula.txt"), "eula=true");

        // Create ops.json if operator is specified
        if (!string.IsNullOrEmpty(profile.OperatorUsername))
        {
            await CreateOpsJsonAsync(profile);
        }
    }

    private async Task CreateServerPropertiesAsync(ServerProfile profile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#Minecraft server properties");
        sb.AppendLine($"#Generated by EzCraft Mod Manager on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine($"motd={EscapeMotd(profile.Motd)}");
        sb.AppendLine($"server-port={profile.Port}");
        sb.AppendLine($"max-players={profile.MaxPlayers}");
        sb.AppendLine($"gamemode={profile.GameMode}");
        sb.AppendLine($"difficulty={profile.Difficulty}");
        sb.AppendLine($"pvp={profile.EnablePvP.ToString().ToLower()}");
        sb.AppendLine($"white-list={profile.EnableWhitelist.ToString().ToLower()}");
        sb.AppendLine($"view-distance={profile.ViewDistance}");
        sb.AppendLine("online-mode=true");
        sb.AppendLine("enable-command-block=true");
        sb.AppendLine("spawn-protection=0");
        sb.AppendLine("allow-flight=true");
        sb.AppendLine($"level-name=world");

        var propertiesPath = Path.Combine(profile.ServerPath, "server.properties");
        await File.WriteAllTextAsync(propertiesPath, sb.ToString());
    }

    private async Task CreateOpsJsonAsync(ServerProfile profile)
    {
        var ops = new[]
        {
            new
            {
                uuid = "00000000-0000-0000-0000-000000000000",
                name = profile.OperatorUsername,
                level = 4,
                bypassesPlayerLimit = true
            }
        };

        var json = JsonConvert.SerializeObject(ops, Formatting.Indented);
        var opsPath = Path.Combine(profile.ServerPath, "ops.json");
        await File.WriteAllTextAsync(opsPath, json);
    }

    private string EscapeMotd(string motd)
    {
        return motd
            .Replace("\\", "\\\\")
            .Replace("\n", "\\n")
            .Replace("\"", "\\\"");
    }

    public async Task<List<InstalledMod>> ScanInstalledModsAsync(string modsFolder)
    {
        var mods = new List<InstalledMod>();

        if (!Directory.Exists(modsFolder)) return mods;

        foreach (var file in Directory.GetFiles(modsFolder, "*.jar"))
        {
            mods.Add(new InstalledMod
            {
                FileName = Path.GetFileName(file),
                Name = Path.GetFileNameWithoutExtension(file),
                FilePath = file,
                InstalledDate = File.GetCreationTime(file),
                IsEnabled = true
            });
        }

        // Check for disabled mods (.jar.disabled)
        foreach (var file in Directory.GetFiles(modsFolder, "*.jar.disabled"))
        {
            mods.Add(new InstalledMod
            {
                FileName = Path.GetFileName(file),
                Name = Path.GetFileNameWithoutExtension(file).Replace(".jar", ""),
                FilePath = file,
                InstalledDate = File.GetCreationTime(file),
                IsEnabled = false
            });
        }

        return mods;
    }

    public async Task ToggleModAsync(InstalledMod mod)
    {
        var currentPath = mod.FilePath;
        string newPath;

        if (mod.IsEnabled)
        {
            // Disable: rename .jar to .jar.disabled
            newPath = currentPath + ".disabled";
        }
        else
        {
            // Enable: remove .disabled extension
            newPath = currentPath.Replace(".disabled", "");
        }

        if (File.Exists(currentPath))
        {
            File.Move(currentPath, newPath);
            mod.FilePath = newPath;
            mod.IsEnabled = !mod.IsEnabled;
        }
    }

    public async Task DeleteModAsync(InstalledMod mod)
    {
        if (File.Exists(mod.FilePath))
        {
            File.Delete(mod.FilePath);
        }
    }
}
